# Oldest version of Ruby supported by the Debugger.
ruby_version: 1.9

# Ignore some rules that are only valid in
# newer versions of Ruby.
ignore:
  - '**/*':
    - Style/SafeNavigation # The & nil check is not available until Ruby 2.3.
    - Lint/IncompatibleIoSelectWithFiberScheduler # Couldn't get this recommend fix to work in the interface.rb non_blocking_gets method.