language: ruby
dist: trusty
matrix:
  fast_finish: true
  include:
    - os: linux
      rvm: 3.0.1
    - os: osx
      rvm: 3.0.1
    - os: linux
      rvm: 2.7.3
    - os: osx
      rvm: 2.7.3
    - os: linux
      rvm: 2.6.7
    - os: osx
      rvm: 2.6.7
    - os: linux
      rvm: 2.5.9
    - os: osx
      rvm: 2.5.9
    - os: linux
      rvm: 2.4.10
    - os: osx
      rvm: 2.4.10
    - os: linux
      rvm: 2.3.8
    - os: linux
      rvm: 2.2.10
    - os: linux
      rvm: 2.1.10
    - os: linux
      rvm: 2.0.0
    - os: linux
      rvm: 1.9.3
    - os: linux
      rvm: 1.8.7
