## Calculates the next version number.  Assumes
## that the code has already been checked out and that
## the fetch-depth is zero:
##
##  uses: actions/checkout@v2
##  with:
##    fetch-depth: 0
##
## More details: https://gitversion.net/docs/reference/requirements
#
#name: 'Calculate Version'
#description: 'Calculate the next version number using GitVersion.'
#
#outputs:
#  version_formats:
#    description: 'The various formats for the version.  See GitVersion for more details.'
#    value: ${{ steps.random-number-generator.outputs }}
#
#runs:
#  using: "composite"
#  steps:
#      - name: Install .NET Core 6
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: '6.0.x'
#
#      - name: Install GitVersion
#        uses: gittools/actions/gitversion/setup@v0.9.13
#        with:
#          versionSpec: '5.10.3'
#
#      - name: GitVersion Config
#        uses: gittools/actions/gitversion/execute@v0.9.13
#        with:
#          useConfigFile: true
#          additionalArguments: '/showConfig'
#
#      - name: Determine Version
#        uses: gittools/actions/gitversion/execute@v0.9.13
#        id: gitversion
#        with:
#          useConfigFile: true